name: Build

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install requirements with PIP
      run: pip install -r requirements.txt
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Build mii2studio
      run: pyinstaller mii2studio.spec
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.os }}
        path: dist
